# Generated by Django 4.2.11 on 2024-04-13 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_productreview_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CartOrderItems',
            new_name='CartOrderProducts',
        ),
    ]
