# Generated by Django 4.2.11 on 2024-04-13 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_cartorderitems_cartorderproducts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CartOrderProducts',
            new_name='CartOrderItems',
        ),
    ]
